- name: Deploy tuic-server on singal control node
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
    ansible_user: root
    tunic_domain: YOUR_DOMAIN
  tasks:
    - name: Install certbot with package manager
      package:
        name: certbot
        state: latest

    - name: Get tunic.py
      action: get_url
      args:
        url: https://raw.githubusercontent.com/QIN2DIM/tuic-installer/main/tunic.py
        dest: /tmp/tunic.py

    - name: Tunic install
      command: "python3 /tmp/tunic.py install -d {{ tunic_domain }}"
      register: install_result

    - name: Check result of tunic-install
      debug:
        var: install_result.stdout_lines
